<?php

return [
    'id' => 'dbTable',
    'namespace' => '$.admin.table',
    'template' => [
        'script' => 'admin::preset.dbtable.script',
        'search' => 'admin::preset.dbtable.search',
        'button' => 'admin::preset.dbtable.button',
    ],
    'totalField' => 'total',
    'classes' => 'table table-bordered table-hover table-nowrap table-striped',
    'batch' => false,
    'method' => 'post',
    'cache' => false,
    'dataField' => 'list',
    'sortable' => true,
    'clickToSelect' => true,
    'pagination' => true,
    'sidePagination' => 'server',
    'pageSize' => 15,
    'pageNumber' => 1,
    'pageList' => [15, 30, 50, 100],
    'paginationLoop' => false,
    'showJumpTo' => true,
    'queryParamsType' => 'limit',
    'presetParams' => [],
    'search' => true,
    'searchOnEnterKey' => true,
    'searchPanel' => true,
    'searchPanelOpen' => false,
    'searchTemplate' => 'dbSearchTemplate',
    'loadingFontSize' => 20,
    'ajax' => '$.admin.table.ajax',
    'actionName' => '_action',
    'actionEvent' => 'action',
    'searchForm' => 'dbSearchForm',
    'searchList' => 'searchs',
    'showColumns' => true,
    'showColumnsToggleAll' => true,
    'showColumnsSearch' => true,
    'minimumCountColumns' => 2,
    'showRefresh' => true,
    'showToggle' => false,
    'showFullscreen' => true,
    'idField' => 'id',
    'selectItemName' => 'selects',
    'toolbar' => '#toolbar',
    'toolbarButton' => 'btn btn-primary',
];
